import sqlite3
import pickle
from memory import Memory
import torch


class DBConnection:
    """Handles the SQLite database connection and operations for the LLM memory subsystem.

    This class provides the interface for creating the memory schema, inserting new
    memories with serialized vector embeddings, and retrieving the full memory bank.

    Attributes:
        con (sqlite3.Connection): The active connection to the SQLite database file.
        cur (sqlite3.Cursor): The cursor used to execute SQL commands.
    """

    def __init__(self):
        """Initializes the database connection and ensures the schema exists."""
        self.con = sqlite3.connect("memory.db")
        self.cur = self.con.cursor()

        # Create the memories table if it doesn't already exist on disk.
        # The embedding is stored as a BLOB because SQLite cannot natively handle vector arrays.
        self.cur.execute("""
            CREATE TABLE IF NOT EXISTS memories (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                content TEXT NOT NULL,
                embedding BLOB NOT NULL,
                timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                importance INTEGER DEFAULT 1
            );
        """)

        # Commit the DDL statement to save the table structure to the database file.
        self.con.commit()

    def retrieve_all_memories(self) -> list[Memory]:
        """Retrieves and deserializes all memories from the database.

        This method performs a full table scan, pulling every stored memory and
        unpickling the vector embeddings back into Python lists.

        Returns:
            list[Memory]: A list of Memory, where each Memory represents a row
                from the database and contains the keys 'content', 'embedding',
                and 'importance'.
        """
        # Fetch ALL rows from the database (Setup for an O(n) scan)
        self.cur.execute("SELECT content, embedding, importance FROM memories")
        rows = self.cur.fetchall()

        all_memories = []

        # Iterate through the results to process the BLOB data
        for row in rows:
            content, embedding_blob, importance = row

            # Deserialize the BLOB back into a usable Python list of floats
            mem_vector = pickle.loads(embedding_blob)

            # Reconstruct the row as a dictionary for easy access in the application layer
            all_memories.append(
                Memory(
                    content=content,
                    embedding=mem_vector,
                    importance=importance,
                )
            )

        return all_memories

    def store_memory(self, memory: Memory):
        """Serializes and inserts a new Memory object into the database.

        Args:
            memory (Memory): The memory data class containing the text content,
                the float vector embedding, and the importance weight.
        """
        # Serialize the embedding vector into raw bytes (BLOB) so SQLite can store it
        embedding_blob = pickle.dumps(memory.embedding)

        # Execute the INSERT statement using parameterized queries (?) to prevent SQL injection
        self.cur.execute(
            """
            INSERT INTO memories (content, embedding, importance)
            VALUES (?, ?, ?)
        """,
            (memory.content, embedding_blob, memory.importance),
        )

        # Commit the transaction to durably save the new row to the database file
        self.con.commit()


if __name__ == "__main__":
    # Example usage / Testing block
    connection = DBConnection()

    # Create a dummy memory object for testing
    memory = Memory(
        content="This will eventually be both the user's query and the AI response concatenated into one big string",
        embedding=torch.tensor(
            [1.2, 2.3, 3.4], dtype=torch.float32
        ),  # data generated by sentence-transformers
        importance=1,  # this is a counter for how many times this memory was accessed, it can be used later for pruning unused memories
    )

    # Store the dummy memory
    connection.store_memory(memory)

    # Retrieve all stored memories to verify the insertion and deserialization worked
    memories = connection.retrieve_all_memories()

    print(memories)
