from pydantic import BaseModel


class Memory(BaseModel):
    """Represents a single memory unit within the LLM memory subsystem.

    This model defines the structure of a memory before it is serialized
    and stored in the database.

    Attributes:
        content (str): The raw text content of the user input and LLM response.
        embedding (list[float]): The representation of the content.
        importance (int): The weight or access frequency of the memory. Defaults to 1.
    """

    content: str
    embedding: list[float]
    importance: int


if __name__ == "__main__":
    new_memory = Memory(
        content="This will eventually be both the user's query and the AI response concatenated into one big string",
        embedding=[1.2, 2.3, 3.4],  # data generated by sentence-transformers
        importance=1,  # this is a counter for how many times this memory was accessed, it can be used later for pruning unused memories
    )
