from pydantic import BaseModel
import uuid
import time


class Memory(BaseModel):
    id = uuid.uuid4()
    content: str
    embedding: str
    timestamp: time.now()
    importance: int


if __name__ == "__main__":
    new_memory = Memory(
        content="This will eventually be both the user's query and the AI response concatenated into one big string",
        embedding="embedding value",  # this is the embedding generated by sentence-transformers
        importance=1,  # this is a counter for how many times this memory was accessed, it can be used later for pruning unused memories
    )
