from pydantic import BaseModel


class Memory(BaseModel):
    content: str
    embedding: list[float]
    importance: int


if __name__ == "__main__":
    new_memory = Memory(
        content="This will eventually be both the user's query and the AI response concatenated into one big string",
        embedding=[1.2, 2.3, 3.4],  # data generated by sentence-transformers
        importance=1,  # this is a counter for how many times this memory was accessed, it can be used later for pruning unused memories
    )
